### ISSUE TITLE
Entry file specified in package.json > main does not exist

### ISSUE THREAD

**Issue by johannes-lindgren** [storyblok/storyblok-design-system#346]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

The `main` field in the `package.json` file specifies the entry point. The value is 

[package.json > main](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#main)
```json
"main": "dist/storyblok-design-system.common.js",
```   

However, the dist folder does not contain such a file. It does contain a file called `design-system.common.js`.

The consequence is that it is not possible to use the package. 

## Expected Behavior

The main field should point to a build file that exists.

## Current Behavior

The main field points to a non-existing file, `dist/storyblok-design-system.common.js`

## Steps to Reproduce

Navigate to the `dist/` directory on [npm](https://www.npmjs.com/package/@storyblok/design-system?activeTab=explore).

Compare this with the main field in the package.json file: https://github.com/storyblok/storyblok-design-system/blob/master/package.json#L19

## Related Issue

The [readme](https://www.npmjs.com/package/@storyblok/design-system?activeTab=readme) refers to a non-existing CSS file, 
`dist/storyblok-design-system.css`

**Comment by ademarCardoso** [comment]
Hello my friend, thanks to report the problem.

This happened because we are updating the `DS` to work with `vue 3` and this difference in the name ended up not being resolved.
This file that appears in **NPM** comes from the branch that is being worked on for the next `vue` as I said. the path that `package.json` does not exist in **NPM** is because it is in develop or master.

We will resolve this issue shortly, thanks for reporting.

cc: @johannes-lindgren @lisilinhart

**Comment by lisilinhart** [comment]
@johannes-lindgren it should be fixed in the new version https://www.npmjs.com/package/@storyblok/design-system/v/3.4.2
